Month 7/step 2
readmecode/react-burger pull request #1
Opened 2022-11-13 11:29 UTC by readmecode

pull request for review

2022-11-13 14:36 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы провели **хорошую** работу на первом этапе вашего нового проекта, добро пожаловать в мир Реакта! В рамках вашего кода используются **современные** функциональные компоненты, хорошо соблюдается **семантика**, основная часть вёрстки **соответствует** макету, CSS **следует принципам** БЭМ-а, так держать 👍 

Тем не менее, для успешной сдачи спринта вам следует внимательно изучить предложенные в рамках ревью комментарии и **внести необходимые правки**, в том числе обратив внимание на следующие моменты:

**Нужно исправить по коду:**

- Модальное окно следует закрывать также и при нажатии вне его (при нажатии на подложку `ModalOverlay`, сейчас это действие не происходит;
- Следует описать полностью `PropTypes` с указанием **всех** пропсов в компонентах, в которых они присутствуют;
- Следует убрать инлайновую стилизацию и указывать в компонентах классы с нужными стилями;
- Не следует использовать пустой объект для отсутствующего значения, вместо это применяйте `null` (пример см. в `App.jsx`)
- Обратите внимание на правила наименования переменных (пример см. в `App.jsx`)
- При выполнении запроса следует обеспечить проверку его успешности, ошибка в методе `catch` появится только, если возникли проблемы на уровне браузера;
- Не следует передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг;
- Следует удалить вывод булок в начинку конструктора ингредиентов;

**Нужно исправить в вёрстке:**

- В конструкторе ингредиентов присутствуют четыре булки (https://disk.yandex.ru/i/CfooYpRd-koKOA);
- Следует убрать вертикальный скролл всей страницы (https://disk.yandex.ru/i/hXkhvno7bHA2cA);
- Счетчики у некоторых ингредиентов в списке ингредиентов заезжают на скролл (https://disk.yandex.ru/i/v7T19V0Rq2KsUQ);
- У хедера задний фон задан другим цветом, относительно заднего фона приложения, согласно дизайну (https://disk.yandex.ru/i/cNcBfxZAF8gGzg);
- Цвет неактивной ссылки в хедере должен быть серым, согласно дизайну (https://disk.yandex.ru/i/LMOR36M2XRD65w);
- Текст цены ингредиента и иконки валюты должны быть центрированы вертикально относительно друг друга (https://disk.yandex.ru/i/KKF8L91rJ_VQRw);
- Следует центрировать логотип относительно центра между конструктором и списком ингредиентов, согласно дизайну (https://disk.yandex.ru/i/lKn2DZnZk3sgXQ);

Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- Распространенной практикой именования файлов и папок в проекте является стиль `kebab-case` - не используются заглавные буквы, а резделение слов в названии производится за счет тире. Это позволяет избежать ошибок, когда в регистро независимых файловых системах проект собирается, а на других нет;
- Для уменьшения дублирования кода, отвечающего за рендер, его повторяющиеся части  имеет смысл выносить в отдельные компоненты (например карточка ингредиента);
- Имеет смысл описать полный вид объекта ингредиента и вынести его в отдельную константу, чтобы переиспользовать в `PropTypes` нескольких компонентов и не дублировать код;
- Код обращения к серверу целесообразно вынести в отдельный файл, т.к. методов будет становится в будущем всё больше и их будет очень удобно контролировать в рамках одного места;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга, хорошего настроения и отличных выходных!** 🐈

2022-11-13 14:36 UTC, randomroot commented on src/components/App/App.jsx
> +      return fetch(`${apiServer}`)
🟡 **Можно улучшить:**

В дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции:

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-11-13 14:36 UTC, randomroot commented on src/components/App/App.jsx
> +  const apiServer = "https://norma.nomoreparties.space/api/ingredients";
🟡 **Можно улучшить:**

Вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`. Так вы сможете переиспользовать базовый адрес в нескольких функциях в будущем

2022-11-13 14:36 UTC, randomroot commented on src/components/App/App.jsx
> +  const [ingrData, setIngrData] = useState({});
🔴 **Нужно исправить:**

**Здесь и далее по коду** не следует использовать пустой объект для отсутствующего значения, вместо это применяйте `null` - так вы избежите возможных проблем в будущем, связанных с возможным обращением по несуществующим ключам, особенно, когда есть вложенность.

2022-11-13 14:36 UTC, randomroot commented on src/components/App/App.jsx
> +  const [brgingr, setBrgingr] = useState(true);
🔴 **Нужно исправить:**

1) **Здесь и далее по коду** название переменных и функций внутри компонентов и других функций следует задавать в стиле `camelCase`, в случае словосочетаний - каждое слово начинать с большой буквы `setBrgIngr`;
2) Переменные `brgingr` и `brgrconstr` не следует хранить в родительском компоненте, т.к. они используются только в своих соответствующих компонентах. Перенесите их в `BurgerIngredients` и `BurgerConstructor` соответственно

🟡 **Можно улучшить:**

1) Не целесообразно сокращать названия слов в переменных, т.к. ухудшается читабельность кода;
2) Название должно отражать, что хранит в себе переменная, в частности сходу другие разработчики вероятно не смогут быстро понять, что именно она означает. Плюс, логические переменные следует начинать с префикса `is`: например здесь хорошим названием будет `isIngredientModalOpen`;

2022-11-13 14:36 UTC, randomroot commented on src/components/App/App.jsx
> +        .then((res) => res.json())
🔴 **Нужно исправить:**

При выполнении запроса следует обеспечить проверку его успешности, ошибка в методе catch появится только, если возникли проблемы на уровне браузера (например нет сети), а если сервер вернет ошибку, то он не отработает. Поэтому перед преобразованием результата в JSON нужно вызвать метод res.ok (см. https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch)

2022-11-13 14:36 UTC, randomroot commented on src/components/AppHeader/AppHeader.jsx
> +        <button
🔴 **Нужно исправить:**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например:
```jsx
<a href="#" class="......">
   <BurgerIcon type="primary" /> Конструктор
</a>
```
В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

2022-11-13 14:36 UTC, randomroot commented on src/components/ModalOverlay/ModalOverlay.jsx
> +    <button className={mdloverlayStyle.overlay}>
🔴 **Нужно исправить:**

Подложка следует сделать простым `div`-ом, а не кнопкой, согласно предназначению (просто отображать задний фон и отвечать на `onClick`).

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      <Modal state={state} setState={setState}>
🔴 **Нужно исправить:**

Не следует передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```jsx
{isOpen && (
    компонент открываемого попапа
)}
```

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
🔴 **Нужно исправить:**

**Здесь и далее по коду:** Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2022-11-13 14:36 UTC, randomroot commented on src/components/IngredientDetails/IngredientDetails.jsx
> +export default IngredientDetails;
🔴 **Нужно исправить:**

Следует описать `PropTypes` у компонента

2022-11-13 14:36 UTC, randomroot commented on src/components/Modal/Modal.jsx
> +    document.getElementById("modalwindow")
🟡 **Можно улучшить:**

Искомый элемент можно записать в константу и переиспользовать её далее:

```js
const MODAL_ROOT = document.getElementById("modalwindow");

const Modal = ({ children, state, setState }) => {
...
```

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      name: PropTypes.string,
🔴 **Нужно исправить:**

Обязательные параметры, в том числе и вложенные следует передавать с `isRequired`: 

```js
name: PropTypes.string.isRequired // т.к. всегда присутствует в объекте
```

🟡 **Можно улучшить:**

Имеет смысл описать полный вид объекта ингредиента и вынести его в отдельную константу, чтобы переиспользовать в `PropTypes` нескольких компонентов и не дублировать код

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const [current, setCurrent] = React.useState("one");
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                  text={item.name}
🔴 **Нужно исправить:**

У булок должен присутствовать окончание `(верх)` или `(низ)` согласно дизайну и положению булки

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +          {data.map(
🔴 **Нужно исправить:**

1) Следует удалить вывод булок в начинку конструктора ингредиентов;
2) Дублирования кода выше можно избежать, если применить предварительно функцию `.filter` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) и получить новый массив без булок, а его уже функцией `.map` вывести на рендер

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                    type={""}
🟡 **Можно улучшить:**

Пропс `type` является необязательным, поэтому его можно безопасно убрать, вместо указания пустой строки

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +                  <div className={burgIngrStyle.item}>
🟡 **Можно улучшить:**

Обратите внимание, что код каждой карточки ингредиента совпадает, поэтому имеет смысл вынести его в отдельный компонент, например `BurgerIngredient` (`burger-ingredient.jsx`)

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  state,
🟡 **Можно улучшить:**

Переменная `state` излишняя, т.к. вы можете ориентироваться на наличие данных в переменной `ingrData` для отображения модального окна

2022-11-13 14:36 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +        <h2 className={burgIngrStyle.burgingridients__menu__title}>Булки</h2>
🟡 **Можно улучшить:**

Обратите внимание, что код каждой категории ингредиентов совпадает, поэтому имеет смысл вынести его в отдельный компонент, например `BurgerIngredientsCategory` (`burger-ingredients-category.jsx`)

2022-11-17 08:00 UTC, randomroot requested changes
**Здравствуйте!**

Вы внесли **немало** правок для исправления выявленных в работе неточностей, а также **улучшили** качество своего кода, однако для окончательного завершения работы над спринтом вам следует провести еще один ряд **корректировок**, согласно ревью, связанных в том числе со следующими моментами:

- Следует убрать вертикальный скролл всей страницы;
- Согласно правилам семантики внутри `<a>` не может располагаться `<button>`, следует заменить кнопки в хедере на ссылки;
- Следует скорректировать (есть лишние пропсы или отсутствуют часть из них) или описать полностью отсутствующие `PropTypes` у нескольких компонентов;
- Константы вне компонентов/функций следует именовать в стиле `UPPER_CASE`, за исключением констант описывающих `PropTypes`;
- Не следует передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг (см. BurgerConstructor.jsx);
- Не следует использовать при описании `PropTypes.object`, т.к. он позволяет передать абсолютно любой объект, даже если он не соответствует внутренней логике компонента. Опишите ожидаемый объект через `PropTypes.shape`;

**Хорошего вам дня!** 🐈

2022-11-17 08:00 UTC, randomroot commented on src/utils/burger-api.js
> +const burgerApi = "https://norma.nomoreparties.space/api";
🔴 **Нужно исправить:**

Константы вне компонентов/функций следует именовать в стиле `UPPER_CASE`, за исключением констант описывающих `PropTypes`

2022-11-17 08:00 UTC, randomroot commented on src/components/OrderDetails/OrderDetails.jsx
> +OrderDetails.propTypes = {
🔴 **Нужно исправить:**

`pic` не передается через пропс, а импортируется, поэтому `PropTypes` для данного компонента не требуются

2022-11-17 08:00 UTC, randomroot commented on src/components/ModalOverlay/ModalOverlay.jsx
> +const ModalOverlay = ({ children, setState }) => {
🔴 **Нужно исправить:**

У ModalOverlay не должно быть children, это просто компонент подложки а не контейнер`.
Плюс сейчас вы ничего не передаете туда :)

2022-11-17 08:00 UTC, randomroot commented on src/components/ModalOverlay/ModalOverlay.jsx
> +ModalOverlay.propTypes = {
🔴 **Нужно исправить:**

Не описан пропс `setState`

2022-11-17 08:00 UTC, randomroot commented on src/components/IngredientDetails/IngredientDetails.jsx
> +  ingrData: PropTypes.object,
🔴 **Нужно исправить:**

Не следует использовать при описании `PropTypes.object`, т.к. он позволяет передать абсолютно любой объект, даже если он не соответствует внутренней логике компонента. Опишите ожидаемый объект через `PropTypes.shape`

2022-11-17 08:00 UTC, randomroot commented on src/utils/burger-api.js
> +function getIngredients(setData) {
🟡 **Можно улучшить:**

Из данной функции целесообразно возвращать значение, вместо передачи параметра `setData`, чтобы сделать данную функцию независимой от реактовских историй

2022-11-17 08:00 UTC, randomroot commented on src/components/AppHeader/AppHeader.jsx
>          <button
🔴 **Нужно исправить:**

Согласно правилам семантики внутри `<a>` не может располагаться `<button>`, в предыдущем ревью предлагалось именно заменить второе на первое

2022-11-17 08:00 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +const BurgerItem = ({ componentItem, bunType, isLocked, bunTypePart }) => {
🔴 **Нужно исправить:**

Для данного компонента следует описать его `PropTypes`

🟡 **Можно улучшить:**

Не рекомендуется хранить несколько компонентов в рамках одного файла, лучше придерживаться принципа - один файл = один компонент, это поможет улучшить читаемость вашего кода и упростить его дальнейшее тестирование

2022-11-17 08:00 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                componentItem={findBun(element._id)}
🔴 **Нужно исправить:**

Здесь не нужно создавать еще одну функцию для поиска данных компонента, вся необходимая информация у вас содержится в переменной `element`

2022-11-17 08:00 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                bunType={""}
🟡 **Можно улучшить:**

Пропсы можно сделать необязательными, тогда вы сможете просто не указывать их, вместо передачи пустой строки

2022-11-17 08:00 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      {setState && (
🔴 **Нужно исправить:**

`setState` всегда будет приводиться к значению `true` т.к. эта функция из хука и она всегда существует.

В рамках предыдущего меню было предложено использовать условный рендеринг, убрав состояние из `Modal`:

Не следует передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```jsx
{isOpen && (
    <Modal onClose={() => setState(false)}>
      <OrderDetails />
    </Modal>
)}
```

2022-11-18 07:06 UTC, randomroot requested changes
**Добрый день!**

Часть исправлений были внесены, однако остаются еще несколько замечаний, которые необходимо скорректировать. Обратите внимание, что работа будет принята только после внесения всех изменений:

- Следует исправить комментарии из категории "Нужно исправить" из предыдущего ревью:
  - **Следует убрать вертикальный скролл всей страницы;** 
  - Нет описания PropTypes у компонента `BurgerItem`;
  - Реализацию открытия модального окна следует сделать через условный рендеринг, скорректировав текущую реализацию (т.к. сейчас проверка идёт через `setState` который всегда `true`);
  - Функция `findBun` в компоненте `BurgerConstructor` осуществляет поиск элемента в массиве, который вы проходите с помощью функции `map` и по факту получаете уже искомый элемент в параметре `element`, поэтому она является излишней. Плюс, из названия можно предположить, что идёт поиск булки, но это не так;
- Вместо `PropTypes.array` следует указать уточненную типизацию через `arrayOf` и `shape` т.к. в текущей реализации нет ограничений по типу передаваемых в массиве элементов;
- Следует поправить `PropTypes` в компоненте `ModalOverlay.jsx`;

**Хорошего вам дня!** 🐈

2022-11-18 07:06 UTC, randomroot commented on src/components/ModalOverlay/ModalOverlay.jsx
> +  setState: PropTypes.element
🔴 **Нужно исправить:**

`setState` является функцией, а не React элементом, следует изменить его `PropTypes`

2022-11-18 07:06 UTC, randomroot commented on src/components/ModalOverlay/ModalOverlay.jsx
> +      {}
🟡 **Можно улучшить:**

Имеет смысл убрать пустые скобки

2022-11-18 07:06 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  data: PropTypes.array.isRequired,
🔴 **Нужно исправить:**

Здесь и ниже вместо `PropTypes.array` следует указать уточненную типизацию через `arrayOf` и `shape` т.к. в текущей реализации нет ограничений по типу передаваемых в массиве элементов;

```
PropTypes.arrayOf(
    PropTypes.shape({
```

2022-11-18 11:08 UTC, readmecode commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  data: PropTypes.array.isRequired,
Несколько вопросов:
1) "Следует убрать вертикальный скролл всей страницы" - на разрешении 1900 и ниже нет вертикального скролла, подскажите что нужно сделать? 

2) "Реализацию открытия модального окна следует сделать через условный рендеринг, скорректировав текущую реализацию (т.к. сейчас проверка идёт через setState который всегда true)" - не получается реализовать данную функциональность

В обоих случаях как я понимаю у других студентов успешно принимают с такой реализацией как у меня оба пункта

2022-11-18 14:23 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  data: PropTypes.array.isRequired,
**Добрый день!**

_"на разрешении 1900 и ниже нет вертикального скролла, подскажите что нужно сделать?"_

  ![image](https://user-images.githubusercontent.com/15111821/202721101-6cbc246f-f478-45d0-a0ba-42d6bfb11b3b.png)

**Пример наличия вертикального скролла:** высота 847px [Chrome] (около 900px высота примерно в обычном браузере у пользователя отображается, при разрешении экрана 1920x1080). В полноэкранном режиме такой проблемы, действительно, нет, но всё-таки не так много людей пользуются таким режимом.

Поэтому вёрстку лучше скорректировать, например вы можете **динамически** в CSS вычислять максимальную высоту списка ингредиентов `max-height` с помощью `calc` используя `100vh` как основу, используя в качестве вычитаемых значений размеры отступов, высоты хедера и т.п. параметров, которые имею фиксированную ширину;

---

_"не получается реализовать данную функциональность"_

 У вас сейчас практически всё сделано для этого. Просто замените `{ setState && <Modal ...}` на `{ state && <Modal ...>` - то есть теперь отслеживание идёт по статусу переменной `state`, а внутри `Modal` просто нужно убрать проверки на открытость и считать, что если `Modal` рендерится - значит он точно в открытом состоянии.
Проблема в текущем состоянии что у вас есть условие как во внешнем мире, так и внутри еще проверка, т.е. дублирование функциональности, а предложенный выше способ решит её :)

2022-11-18 16:12 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

**По комментариям на тему вертикального скролла и условного рендеринга**: по согласованию со старшим ревьюером, перенесли их в категорию "Можно лучше", после вашего комментария описал предложения, как можно поправить ситуацию, но реализация остаётся на ваше усмотрение :)

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-11-18 16:12 UTC, randomroot commented on src/components/IngredientDetails/IngredientDetails.jsx
> +/*
🟡 **Можно улучшить:**

Следует раскомментировать `propTypes`, оставив только `shape` без `arrayOf`:

```jsx
IngredientDetails.propTypes = {
  ingrData: PropTypes.shape({
      name: PropTypes.string.isRequired,
      image: PropTypes.string.isRequired,
      calories: PropTypes.number.isRequired,
      proteins: PropTypes.number.isRequired,
      fat: PropTypes.number.isRequired,
      carbohydrates: PropTypes.number.isRequired,
    })
};
```

2022-11-18 16:12 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  componentItem: PropTypes.objectOf(
🟡 **Можно улучшить:**

В данном случае `PropTypes.objectOf` не требуется, т.к. `shape` уже описывает структуру данных :)

2022-12-05 14:29 UTC, merged